name: zilbit
description: A P2P crypto trading platform

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  get: ^4.6.1
  flutter_svg: ^1.0.3
  flutter_screenutil: ^5.0.2
  font_awesome_flutter: ^10.0.0
  bouncing_widget: ^2.0.0
  intl_phone_field: ^3.0.1
  numeric_keyboard: ^1.1.0
  pinput: ^2.2.4
  flutter_rating_bar: ^4.0.0
  percent_indicator: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
