name: zilbit
description: A P2P crypto trading platform

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  get: ^4.6.1
  flutter_svg: ^1.0.3
  flutter_screenutil: ^5.3.1
  font_awesome_flutter: ^10.0.0
  bouncing_widget: ^2.0.0
  intl_phone_number_input: ^0.7.0+2
  intl_phone_field: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
